accounts/urls.py
from django.urls import path
from .import views
from appointment.views import *

from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
# from accounts.views import *
app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('Patient_register/', views.patient_register, name='Patient_register'),
    path('Doctor_register/', views.doctor_register, name='Doctor_register'),
    path('login/', views.login_view_user, name='login'),
    path('', views.home_page_view, name='index'),

    path('logout/', views.logout_view, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_form.html", success_url=reverse_lazy("password_reset_complete")),
         name="password_reset_confirm"),  # 3
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html", success_url=reverse_lazy("password_reset_done"), email_template_name='registration/forgot_password_email.html'),
         name="reset_password"),     # 1
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"),
         name="password_reset_done"),    # 2

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_done.html"),
         name="password_reset_complete"),   # 4

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html', success_url=reverse_lazy("password_change_done")),
         name='password_change'),




]

appointment/urls.py
"""
doctor_appointment_system URL Configuration

"""

from django.urls import path
from appointment.views import *
from django.conf import settings
from django.conf.urls.static import static
from appointment import views

app_name = 'appointment'

urlpatterns = [

    # path('', HomePageView.as_view(), name='home'),
    path('service', views.service_view,  name='service'),
    path('<int:pk>/patient/delete/', views.delete_patient, name='delete-patient'),
    path('<int:pk>/doctor/delete/', views.delete_doctor, name='delete-doctor'),
    path('search/', views.search_view, name='search'),
    path('patient/', views.patient_list, name='patient-list'),
    path('doctor-list/', views.doctor_list, name='doctor-list'),

    path('patients/<id>/', views.doctordetails, name='doctor-detail'),
    path('detail/<int:id>/', views.display_cart, name='detail'),
    path('doctordetail/<id>/', views.view_doctor_detail, name='docdetail'),
    path('patient/profile/update/<id>/', views.editprofile, name='patient-profile-update'),
    path('doctor/profile/update/<id>/', views.editprofiledoctor, name='doctor-profile-update'),
    path('payment/<int:id>', views.payment, name = 'payment'),
    path('handlerequest/', views.handlerequest, name = 'handlerequest'),
    path('generateinvoice/<int:pk>/', views.GenerateInvoice.as_view(), name = 'generateinvoice'),
    


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docmed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url,  include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('appointment.urls')),

    url('', include('social_django.urls', namespace='social')),
]

accounts/models.py
from re import T
from django.db import models



from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.utils import timezone
# Create your models here.
from multiselectfield import MultiSelectField


from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.utils.translation import ugettext_lazy as _

from .managers import CustomUserManager
# from appointment.models import Appointment

from django.contrib.auth.models import PermissionsMixin

from django.db.models import Q
# from datetime import timedelta





class LowercaseEmailField(models.EmailField):
    """
    Override EmailField to convert emails to lowercase before saving.
    """
    def to_python(self, value):
        """
        Convert email to lowercase.
        """
        value = super(LowercaseEmailField, self).to_python(value)
        # Value can be None so check that it's a string before lowercasing.
        if isinstance(value, str):
            return value.lower()
        return value

class CustomUser(AbstractBaseUser, PermissionsMixin):
    # username = None
    email = LowercaseEmailField(_('email address'), unique=True)
    name = models.CharField(max_length=255)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    # if you require phone number field in your project
    phone_regex = RegexValidator( regex = r'^\d{10}$',message = "phone number should exactly be in 10 digits")
    phone_number = models.CharField(max_length=255, validators=[phone_regex], blank = True, null=True)  # you can set it unique = True
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M', null=True)
    
    is_Patient = models.BooleanField(default=True)
    is_Doctor = models.BooleanField(default = False)

  


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email
    
    
  

# Model Managers for proxy models
class DoctorManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        #return super().get_queryset(*args, **kwargs).filter(type = CustomUser.Types.Doctor)
        return super().get_queryset(*args, **kwargs).filter(is_Doctor=True)

class PatientManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        #return super().get_queryset(*args, **kwargs).filter(type = CustomUser.Types.Patient)
        return super().get_queryset(*args, **kwargs).filter(is_Patient=True)


# Proxy Models. They do not create a seperate table
class Doctor(CustomUser):
    # default_type = CustomUser.Types.DOCTOR
    is_Doctor = True
    objects = DoctorManager()
    class Meta:
        proxy = True
    
   

    @property
    def showAdditional(self):
        return self.doctoradditional

    @property
    def showAppointment(self):
        return self.appointment
        
    def __str__(self):
        return self.name  
    
class Patient(CustomUser):
    # default_type = CustomUser.Types.PATIENT
    is_Patient= True
    objects = PatientManager()
    class Meta:
        proxy = True 

    

    @property
    def showAdditional(self):
        return self.patientadditional
    @property
    def age(self):
        return self.patientadditional.age

    @age.setter
    def age(self, age):
        self.patientadditional.age = age  
            
    def __str__(self):
        return self.name 

class PatientAdditional(models.Model):
    user = models.OneToOneField(Patient, on_delete = models.CASCADE)
    age = models.CharField(max_length=20)
    profile_photo = models.ImageField(upload_to='patient_profile_photos', blank=True, null=True)
  

class DoctorAdditional(models.Model):
    user = models.OneToOneField(Doctor, on_delete = models.CASCADE)
    location = models.CharField(max_length=20)
    your_expertise =  models.CharField(max_length=20)
  

accounts/views.py
from django.contrib.auth import login, logout,authenticate
from django.shortcuts import redirect, render,HttpResponse
from django.contrib import messages
from django.views.generic import CreateView,ListView
from .form import PatientSignUpForm, DoctorSignUpForm
from django.contrib.auth.forms import AuthenticationForm
from .models import CustomUser, Doctor, DoctorAdditional, PatientAdditional

from django.contrib.auth.views import LoginView, LogoutView

from docmed import settings
from django.core.mail import EmailMessage
from .tokens import account_activation_token
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.contrib.messages.views import SuccessMessageMixin
from appointment.models import Appointment
def register(request):
    return render(request, 'register.html')
def patient_register(request):
    if request.method == 'POST':
        form = PatientSignUpForm(request.POST, request.FILES)
        if form.is_valid():
            user_email = form.cleaned_data.get('email')

            try:
                existing_user = get_user_model().objects.get(email=user_email)
                if not existing_user.is_active:
                    existing_user.delete()
            except get_user_model().DoesNotExist:
                pass

            user = form.save(commit=False)
            # user.is_active = False
            user.save()

            age = form.cleaned_data.get('age')
            profile_photo = form.cleaned_data.get('profile_photo')

            patient_additional = PatientAdditional.objects.create(user=user, age=age, profile_photo=profile_photo)

            # current_site = get_current_site(request)
            # mail_subject = 'Activate your account.'
            # message = render_to_string('acc_active_email.html', {
            #     'user': user,
            #     'domain': current_site.domain,
            #     'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            #     'token': account_activation_token.make_token(user),
            # })
            # to_email = user_email

            try:
                # send_mail(
                #     subject=mail_subject,
                #     message=message,
                #     from_email=settings.EMAIL_HOST_USER,
                #     recipient_list=[to_email],
                #     fail_silently=False,
                # )
                # messages.success(request, "A link has been sent to your email id. Please check your inbox and spam folder.")
                return HttpResponseRedirect(reverse_lazy('accounts:login'))
            except:
                form.add_error(None, 'An error occurred while sending the email. Please try again.')
                messages.error(request, "An error occurred while sending the email. Please try again.")
    else:
        form = PatientSignUpForm()

    context = {'form': form}
    return render(request, 'Patient_register.html', context)

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, CustomUser.DoesNotExist) as e:
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        user.save()
        login(request, user)
        messages.success(request, "Successfully Logged In")
        return redirect(reverse_lazy('accounts:index'))
       
    else:
        return HttpResponse('Activation link is invalid or your account is already Verified! Try To Login')    
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
def doctor_register(request):
    if request.method == 'POST':
        form = DoctorSignUpForm(request.POST)
        if form.is_valid():
            user_email = form.cleaned_data.get('email')

            try:
                existing_user = get_user_model().objects.get(email=user_email)
                if not existing_user.is_active:
                    existing_user.delete()
            except get_user_model().DoesNotExist:
                pass

            user = form.save(commit=False)
            # user.is_active = False
            user.is_Doctor =True
            user.is_Patient= False
            user.save()

            location = form.cleaned_data.get('location')
            your_expertise = form.cleaned_data.get('your_expertise')

            DoctorAdditional.objects.create(user=user, location=location, your_expertise=your_expertise)

            # current_site = get_current_site(request)
            # mail_subject = 'Activate your account.'
            # message = render_to_string('acc_active_email.html', {
            #     'user': user,
            #     'domain': current_site.domain,
            #     'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            #     'token': account_activation_token.make_token(user),
            # })
            # to_email = user_email

            try:
                # send_mail(
                #     subject=mail_subject,
                #     message=message,
                #     from_email=settings.EMAIL_HOST_USER,
                #     recipient_list=[to_email],
                #     fail_silently=False,
                # )
                # messages.success(request, "A link has been sent to your email id. Please check your inbox and spam folder.")
                return HttpResponseRedirect(reverse_lazy('accounts:login'))
            except:
                form.add_error(None, 'An error occurred while sending the email. Please try again.')
                messages.error(request, "An error occurred while sending the email. Please try again.")
    else:
        form = DoctorSignUpForm()

    context = {'form': form}
    return render(request, 'Doctor_register.html', context)


def logout_view(request):
    logout(request)
    return redirect('/')

from django.contrib.auth.views import LoginView

def login_view_user(request):
    return LoginView.as_view(template_name='login.html')(request)



from django.core.paginator import Paginator

def home_page_view(request):
    appointment_list = Appointment.objects.all().order_by('-id')
    paginator = Paginator(appointment_list, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'home': page_obj}
    return render(request, 'index.html', context)

templates/accounts/patient/edit-profile-extra.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}Patient Profile Edit{% endblock %}

{% block content %}

 <div class="container">

    <div class="row justify-content-center">

        <div class="col-lg-5 mb-5 mb-lg-0">
            <center>
                <h3>Edit Profile </h3>
            </center>

            {% if request.user.patientadditional.profile_photo %}
<div class="text-center mb-4">
    <img src="{{ request.user.patientadditional.profile_photo.url }}" alt="Profile Photo" class="img-fluid rounded-circle profile-photo" style="width: 200px; height: 200px;">
</div>
{% endif %}


            <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
                {{ form|bootstrap }}
                {{form1|bootstrap }}
                <div class="row form-group">
                    <div class="col-md-12">
                        <input type="submit" value="Update" class="btn btn-primary btn-md text-white">
                    </div>
                </div>


            </form>


        </div>

    </div>
</div> 




        {% endblock %} 

templates/accounts/patient/edit-profile.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}Patient Profile Edit{% endblock %}

{% block content %}

 <div class="container">

    <div class="row justify-content-center">

        <div class="col-lg-5 mb-5 mb-lg-0">
            <center>
                <h3>Edit Profile </h3>
            </center>



            <form action="" method="POST">{% csrf_token %}
                {{ form|bootstrap }}

                <div class="row form-group">
                    <div class="col-md-12">
                        <input type="submit" value="Update" class="btn btn-primary btn-md text-white">
                    </div>
                </div>
                
            </form>
            <div class="col-md-12">
                <a href="{% url 'appointment:patient-profile-update2' id=request.user.id %}"> Extra
                    Details</a>
                </div>

        </div>

    </div>
</div> 


{% comment %} <div class="main-area">
    <div class="product-cards">
        <h1 style="text-align:center;">Profile Update</h1> {% endcomment %}

        {% comment %} {% for i in patient %} {% endcomment %}
        {% comment %} <div class="row featurette"> {% endcomment %}
            {% comment %} <div class="col-md-2">
                <img src="/media/{{i.product.image}}" class="card-img-top" alt="...">
            </div> {% endcomment %}
            {% comment %} <div class="col-md-7"> {% endcomment %}
                {% comment %} <h2 class="featurette-heading">{{}}</h2>
                <p class="lead">Rs. {{i.product.price}}</p>
                <p class="lead">Quantity- {{i.quantity}}</p> {% endcomment %}
                {% comment %} <form method="POST" action="{% url 'appointment:patient-list'  %}">{% csrf_token %} {% endcomment %}
                {% comment %} <form method="POST" action="{% url 'accounts:patient-profile-update'  %}">{% csrf_token %}
                    <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" id="id_name" name="name" placeholder= "{{patient.name}}">
                   </div> {% endcomment %}
                   {% comment %} <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" id="id_name" name="name" value= "{{i.name}}">
                   </div> {% endcomment %}
                   {% comment %} <form action="" method="POST">{% csrf_token %}
                    {% for field in form %}
                {% if field.name == 'gender' %}

                    <div class="form-group">
                        <label for="gender">Gender</label>
                        <br>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="gender" id="Male "
                                   value="M">
                            <label class="form-check-label" for="male">Male</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="gender" id="Female"
                                   value="F">
                            <label class="form-check-label" for="female">Female</label>
                        </div>
                    </div>

                {% else %}

                    <div class="form-group">
                        <label for="id_{{ field.name }}">{{ field.label }}</label>
                        <input type="{{ field.field.widget.input_type }}"
                               class="form-control"
                               name="{{ field.name }}"
                               id="id_{{ field.name }}"
                               placeholder="{{ patient.name }}">
                    </div>

                      {% endif %}
            {% endfor %}
                    <button class="btn btn-primary" type="submit">Update Quantity</button>
                </form> {% endcomment %}
                {% comment %} <form method="POST" action="{% url 'deletefromcart' %}">{% csrf_token %}
                    <button class="btn btn-primary" type="submit">Delete</button>
                </form> {% endcomment %}
            {% comment %} </div>

        </div>
        <hr> {% endcomment %}
        {% comment %} {% empty %} {% endcomment %}
        {% comment %} <h4>Empty Cart</h4> {% endcomment %}
        {% comment %} {% endfor %} {% endcomment %}



        {% endblock %}

templates/accounts/patient/register.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}Patient registration{% endblock %}


{% block content %}

<div class="container">

<div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <center> <h3>Patient Registration</h3></center>

                    <form action="" method="POST">{% csrf_token %}
                        {% for field in form %}
                    {% if field.name == 'gender' %}

                        <div class="form-group">
                            <label for="gender">Gender</label>
                            <br>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="gender" id="male gender"
                                       value="male">
                                <label class="form-check-label" for="male">Male</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="gender" id="female"
                                       value="female">
                                <label class="form-check-label" for="female">Female</label>
                            </div>
                        </div>

                    {% else %}

                        <div class="form-group">
                            <label for="id_{{ field.name }}">{{ field.label }}</label>
                            <input type="{{ field.field.widget.input_type }}"
                                   class="form-control"
                                   name="{{ field.name }}"
                                   id="id_{{ field.name }}"
                                   placeholder="{{ field.field.widget.attrs.placeholder }}">
                        </div>

                          {% endif %}
                {% endfor %}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Register" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>


                    </form>
                </div>

            </div>
        </div>

{% endblock %}