appointment/urls.py
"""
doctor_appointment_system URL Configuration

"""

from django.urls import path
from appointment.views import *
from django.conf import settings
from django.conf.urls.static import static
from appointment import views

app_name = 'appointment'

urlpatterns = [

    # path('', HomePageView.as_view(), name='home'),
    path('service', views.service_view,  name='service'),
    path('<int:pk>/patient/delete/', views.delete_patient, name='delete-patient'),
    path('<int:pk>/doctor/delete/', views.delete_doctor, name='delete-doctor'),
    path('search/', views.search_view, name='search'),
    path('patient/', views.patient_list, name='patient-list'),
    path('doctor-list/', views.doctor_list, name='doctor-list'),

    path('patients/<id>/', views.doctordetails, name='doctor-detail'),
    path('detail/<int:id>/', views.display_cart, name='detail'),
    path('doctordetail/<id>/', views.view_doctor_detail, name='docdetail'),
    path('patient/profile/update/<id>/', views.editprofile, name='patient-profile-update'),
    path('doctor/profile/update/<id>/', views.editprofiledoctor, name='doctor-profile-update'),
    path('payment/<int:id>', views.payment, name = 'payment'),
    path('handlerequest/', views.handlerequest, name = 'handlerequest'),
    path('generateinvoice/<int:pk>/', views.GenerateInvoice.as_view(), name = 'generateinvoice'),
    


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docmed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url,  include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('appointment.urls')),

    url('', include('social_django.urls', namespace='social')),
]

appointment/forms.py
from django import forms
from .models import Appointment, TakeAppointment


class CreateAppointmentForm1(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateAppointmentForm1, self).__init__(*args, **kwargs)
        self.fields['image'].label = "Image"
        self.fields['start_time'].label = "Start Time"
        self.fields['hospital_name'].label = "Hospital Name"
        self.fields['qualification_name'].label = "Qualification"
        self.fields['institute_name'].label = "Institute"

       

       

        self.fields['start_time'].widget.attrs.update(
            {
                'placeholder': 'Ex : 9 AM',
            }
        )
        self.fields['end_time'].widget.attrs.update(
            {
                'placeholder': 'Ex: 5 PM',
            }
        )
       

        self.fields['hospital_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Hospital Name',
            }
        )

        self.fields['qualification_name'].widget.attrs.update(
            {
                'placeholder': 'Ex : MBBS, BDS',
            }
        )

        self.fields['institute_name'].widget.attrs.update(
            {
                'placeholder': 'Ex : DMC',
            }
        )

    class Meta:
        model = Appointment
        fields = [
        'image',
          'start_time', 'end_time',
                  'hospital_name', 'qualification_name', 'institute_name']

  
class CreateAppointmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateAppointmentForm, self).__init__(*args, **kwargs)
        self.fields['image'].label = "Image"
        self.fields['start_time'].label = "Start Time"
        self.fields['hospital_name'].label = "Hospital Name"
        self.fields['qualification_name'].label = "Qualification"
        self.fields['institute_name'].label = "Institute"

      
        self.fields['start_time'].widget.attrs.update(
            {
                'placeholder': 'Ex : 9 AM',
            }
        )
        self.fields['end_time'].widget.attrs.update(
            {
                'placeholder': 'Ex: 5 PM',
            }
        )
        

        self.fields['hospital_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Hospital Name',
            }
        )

        self.fields['qualification_name'].widget.attrs.update(
            {
                'placeholder': 'Ex : MBBS, BDS',
            }
        )

        self.fields['institute_name'].widget.attrs.update(
            {
                'placeholder': 'Ex : DMC',
            }
        )

    class Meta:
        model = Appointment
        fields = [
        'image',
          'start_time', 'end_time',
                  'hospital_name', 'qualification_name', 'institute_name']

    def is_valid(self):
        valid = super(CreateAppointmentForm, self).is_valid()

        if valid:
            return valid
        return valid

    def save(self, commit=True):
        appointment = super(CreateAppointmentForm, self).save(commit=False)
        if commit:
            appointment.save()
        return appointment


class TakeAppointmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TakeAppointmentForm, self).__init__(*args, **kwargs)
        self.fields['appointment'].label = "Choose Your Doctor"
        self.fields['date'].label = "Date"
        self.fields['time'].label = "Time"
        self.fields['message'].label = "Message"

        self.fields['appointment'].widget.attrs.update(
            {
                'placeholder': 'Choose Your Doctor',
            }
        )

        self.fields['date'].widget.attrs.update(
            {
                'placeholder': 'Date',
            }
        )

        self.fields['time'].widget.attrs.update(
            {
                'placeholder': 'Time',
            }
        )
        self.fields['message'].widget.attrs.update(
            {
                'placeholder': 'Write a short message',
            }
        )

    class Meta:
        model = TakeAppointment
        fields = ['appointment',
         'date',
         'time',
           'message']

    def is_valid(self):
        valid = super(TakeAppointmentForm, self).is_valid()

        if valid:
            return valid
        return valid

    def save(self, commit=True):
        appointment = super(TakeAppointmentForm, self).save(commit=False)
        if commit:
            appointment.save()
        return appointment

appointment/views.py
from datetime import date
from django.shortcuts import render



from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect,HttpResponse
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from accounts.models import Doctor, User,Patient
from .decorators import user_is_patient, user_is_doctor
from django.views.generic import TemplateView, UpdateView, CreateView, ListView, DetailView, DeleteView,View
from django.views.generic.edit import DeleteView, UpdateView
from accounts.form import DoctorProfileUpdateForm2, PatientProfileUpdateForm, DoctorProfileUpdateForm, PatientProfileUpdateForm2
from .forms import CreateAppointmentForm, TakeAppointmentForm
from .models import Appointment, PatientAppointmentTrack, TakeAppointment, Order
from accounts.models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from docmed import settings




        


@login_required
def editprofile(request, id):
    try:
        obj = get_object_or_404(Patient, id=id)
        obj1 = PatientAdditional.objects.get(user=request.user)
    except Patient.DoesNotExist:
        return HttpResponse('Patient not found.')
    except PatientAdditional.DoesNotExist:
        obj1 = PatientAdditional(user=request.user)

    if request.method == 'POST':
        form = PatientProfileUpdateForm(request.POST, instance=obj)
        form1 = PatientProfileUpdateForm2(request.POST,request.FILES or None, instance=obj1)
        if form.is_valid() and form1.is_valid():
            form.save()
            form1.save()
            return HttpResponseRedirect("/" )
    else:
        form = PatientProfileUpdateForm(instance=obj)
        form1 = PatientProfileUpdateForm2(instance=obj1)

    context = {'form': form, 'form1': form1}
    return render(request, "accounts/patient/edit-profile-extra.html", context)


def editprofiledoctor(request,id):
   
    obj1=DoctorAdditional.objects.get(user=request.user)
    obj = get_object_or_404(Doctor, id=id)
 
    # pass the object as instance in form
    form = DoctorProfileUpdateForm(request.POST or None, instance = obj)
    form1 = DoctorProfileUpdateForm2 (request.POST or None, instance = obj1)
    try:
        obj2=Appointment.objects.get(user=request.user)
        form2 = CreateAppointmentForm (request.POST or None,request.FILES or None, instance = obj2)
    except:
        obj2=Appointment.objects.create(user=request.user)
        form2 = CreateAppointmentForm (request.POST or None,request.FILES or None, instance=obj2)

    # 
    if form.is_valid() and form1.is_valid() and form2.is_valid():
        form.save()
        form1.save()
        form2.save()

        return HttpResponseRedirect("/")
 
    # add form dictionary to context
    context={'form':form, 'form1':form1,'form2':form2}
    # context1["form1"] = form1
 
    return render(request, "accounts/doctor/edit-profile.html", context)
@login_required
def display_cart(request,id):
    try:
        qs = TakeAppointment.objects.get(id=id)
        appointment = get_object_or_404(Appointment, id=qs.appointment.id)
        return render(request, "payment/detail.html", {'cart': [appointment], 'id':id})
    except TakeAppointment.DoesNotExist:
        raise Http404("Appointment has already been taken.")

def doctordetails(request,id):
    # context={}
        
   
        if request.method == 'POST':
            appointment = Appointment.objects.get(id=id)
            message = request.POST.get('message')
            date = request.POST.get('date')
            time = request.POST.get('time')
            # 
            t_app = TakeAppointment.objects.create(appointment=appointment, user=request.user,message=message, date=date,time=time) 
            t_app.save()
            # return  redirect(reverse_lazy("appointment:detail"))
            return redirect('appointment:detail', t_app.id)
            # 
        return render(request, 'appointment/take_appointment_detail.html')
    
        #


"""
   For Doctor Profile
"""


# 






# 
def patient_list(request):
    patients = TakeAppointment.objects.filter(appointment__user_id=request.user.id).order_by('-id')
    
    context = {
        'patients': patients,
    }

    return render(request, 'appointment/patient_list.html', context)

def doctor_list(request):
    doctors = TakeAppointment.objects.filter(user__id=request.user.id).order_by('-id')
    
    context = {
        'doctors': doctors,
    }

    return render(request, 'appointment/doctor_list.html', context)




def delete_patient(request, pk):
    appointment = get_object_or_404(TakeAppointment, pk=pk)
    appointment.delete()
    return redirect('appointment:patient-list')

def delete_doctor(request, pk):
    appointment = get_object_or_404(TakeAppointment, pk=pk)
    appointment.delete()
    return redirect('appointment:doctor-list')







#


from django.views.generic import TemplateView

def service_view(request):
    template_name = 'appointment/service.html'
    return render(request, template_name)


from django.views.generic import ListView
from .models import DoctorAdditional

def search_view(request):
    paginate_by = 6
    model = DoctorAdditional
    template_name = 'appointment/search.html'
    context_object_name = 'appointment'

    if request.method == 'GET':
        your_expertise = request.GET.get('your_expertise')
        location = request.GET.get('location')
        queryset = model.objects.filter(
            your_expertise__contains=your_expertise,
            location__contains=location
        )
        context = {
            'appointment': queryset
        }
        return render(request, template_name, context)

# 



import razorpay
razorpay_client = razorpay.Client(auth=(settings.razorpay_id, settings.razorpay_account_id))

from .models import Order
from django.contrib.sites.shortcuts import get_current_site


@login_required
def payment(request, id):
    if request.method == "POST":
        
        cart = TakeAppointment.objects.get(id = id)
        print(cart.id)
    
       
        order = Order.objects.create(take=cart, total_amount = 0)
        final_price= cart.appointment.price
        print(final_price)
        print(order)
       
        
        order.total_amount = final_price
        order.save()

        order_currency = 'INR'

        callback_url = 'http://'+ str(get_current_site(request))+"/handlerequest/"
        print(callback_url)
        notes = {'order-type': "basic order from the website", 'key':'value'}
        razorpay_order = razorpay_client.order.create(dict(amount=final_price*100, currency=order_currency, notes = notes, receipt=order.order_id, payment_capture='0'))
        print(razorpay_order['id'])
        order.razorpay_order_id = razorpay_order['id']
        order.save()
        
        return render(request, 'payment/paymentsummaryrazorpay.html', {'order':order, 'order_id': razorpay_order['id'], 'orderId':order.order_id, 'final_price':final_price, 'razorpay_merchant_id':settings.razorpay_id, 'callback_url':callback_url})
    else:
        return HttpResponse("505 Not Found") 


from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
import os
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import render_to_string
from django.core.mail import EmailMessage



def fetch_resources(uri, rel):
    path = os.path.join(uri.replace(settings.STATIC_URL, ""))
    return path

def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html  = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)#, link_callback=fetch_resources)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None

from django.core.mail import EmailMultiAlternatives
@csrf_exempt
def handlerequest(request):
    if request.method == "POST":
        # try:
        payment_id = request.POST.get('razorpay_payment_id', '')
        order_id = request.POST.get('razorpay_order_id','')
        signature = request.POST.get('razorpay_signature','')
        params_dict = { 
        'razorpay_order_id': order_id, 
        'razorpay_payment_id': payment_id,
        'razorpay_signature': signature
        }
        try:
            order_db = Order.objects.get(razorpay_order_id=order_id)
        except:
            return HttpResponse("505 Not Found")
        order_db.razorpay_payment_id = payment_id
        order_db.razorpay_signature = signature
        order_db.save()
        result = razorpay_client.utility.verify_payment_signature(params_dict)
        if result==None:
            amount = order_db.total_amount * 100   #we have to pass in paisa
            # try:
            razorpay_client.payment.capture(payment_id, amount)
            order_db.payment_status = 1
            order_db.save()

            template = get_template('payment/invoice.html')
            data = {
                'order_id': order_db.order_id,
                'transaction_id': order_db.razorpay_payment_id,
                'user_email': order_db.take.user.email,
                'date': str(order_db.datetime_of_payment),
                'name': order_db.take.user.name,
                'order': order_db,
                'amount': order_db.total_amount,
            }
            html  = template.render(data)
            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)#, link_callback=fetch_resources)
            pdf = result.getvalue()
            filename = 'Invoice_' + data['order_id'] + '.pdf'

            mail_subject = 'Recent Order Details'

templates/appointment/appointment.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Appointment List{% endblock %}



{% block content %}

    <section class="dentist-area section-padding-40-0">

    <div class="container">


      <div class="row">

        <!-- Section Heading -->
        <div class="col-12">
          <div class="section-heading text-center">


            <h3>{{ request.user.first_name }}'s Appointment/s</h3>
            <div class="line"></div>
          </div>
        </div>
      </div>

      <div class="row">
          {% for apt in appointment %}
        <!-- Single Dentist Area -->
        <div class="col-12 col-sm-6 col-md-4">

          <div class="single-dentist-area mb-100">
            <img  style="height: 500px; width: 600px" src="{{ apt.get_image_url }}" alt="">
            <!-- Dentist Content -->
            <div class="dentist-content">
              <!-- Social Info -->
              <div class="dentist-social-info">

              </div>
              <!-- Dentist Info -->
              <div class="dentist-info bg-gradient-overlay">
                <h5>{{ apt.user.name }}</h5>
                <p>{{ apt.user.showAdditional.your_expertise }} Expert</p>
                  <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                  <p>Available {{ apt.start_time }} to {{ apt.end_time }} in {{ apt.hospital_name }}</p>
                  <p> AT {{ apt.user.showAdditional.location }}
                      <i class="fa fa-trash-o" style="color: red" aria-hidden="true"></i>
                      <a href="{% url 'appointment:delete-appointment' apt.id %}">Delete Appointment</a>
                  </p>

              </div>
            </div>
          </div>
        </div>
      {% endfor %}

      </div>
    </div>
  </section>

{% endblock %}

templates/appointment/appointment_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Appointment Delete{% endblock %}

{% block content %}

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-lg-5 mb-5 mb-lg-0">
                <center>
                    <h4 class="highlight">Are you sure you want to delete {{ object.full_name }}'s Appointment?</h4>

                </center>
                <form method="post" enctype="multipart/form-data">{% csrf_token %}


                    <img style="height: 400px; width: 450px" src="{{ object.image.url }}" alt="">
                    </br>
                    </br>
                    <center><input class="btn btn-danger" type="submit" value="Delete">
                    </center>


                </form>
                </br>

            </div>
        </div>
    </div>


{% endblock %}

templates/appointment/appointment_create.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Appointment Create {% endblock %}

{% block content %}

    <section class="dentist-area section-padding-40-0">
<div class="container">

<div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <center> <h3>Create  Appointment</h3></center>

                    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Create" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>


                    </form>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/appointment/doctor_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Patient List{% endblock %}

{% block content %}
    <section class="dentist-area section-padding-50-0">
        <div class="container" style="align-items: center; justify-content: center; display: flex;">
            <div class="col-12 col-sm-6 col-md-4">
                <h3 style="align-items: center; justify-content: center; display: flex;">Patient's Appointments  </h3>
                <br>
                <br>
            </div>
        </div>
    </section>

    <section class="dentist-area section-padding-30-0">
        <div class="container">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col" class="text-center">Profile Photo</th>
                    <th scope="col">Name</th>
                    {% comment %} <th scope="col">Phone Number</th> {% endcomment %}
                    <th scope="col">Message</th>
                    <th scope="col">Date</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for doctor in doctors %}
                    <tr>
                        <td style="vertical-align: middle; display: flex; align-items: center;">
                            <div style="width: 50px; height: 50px; border-radius: 50%; overflow: hidden; margin: 0 auto;">
                                {% if doctor.appointment.user.showAppointment.image %}
                                    <img src="{{ doctor.appointment.user.showAppointment.get_image_url }}" alt="Profile Photo" style="width: 100%; height: 100%; object-fit: cover;">
                                {% else %}
                                    <img src="{% static 'images/default-profile-photo.jpg' %}" alt="Profile Photo" style="width: 100%; height: 100%; object-fit: cover;">
                                {% endif %}
                            </div>
                        </td>
                        <td style="vertical-align: middle;">{{ doctor.appointment.user.name }}</td>
                        {% comment %} <td style="vertical-align: middle;">{{ doctor.user.phone_number }}</td> {% endcomment %}
                        <td style="vertical-align: middle;">{{ doctor.message }}</td>
                        <td style="vertical-align: middle;">{{ doctor.date }}</td>
                        <td style="vertical-align: middle;" >
                            <a href="{% url 'appointment:delete-doctor' doctor.id %}">
                                <i class="far fa-trash-alt" style="visibility: visible;"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}
 

templates/appointment/patient_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Patient List{% endblock %}

{% block content %}
    <section class="dentist-area section-padding-50-0">
        <div class="container" style="align-items: center; justify-content: center; display: flex;">
            <div class="col-12 col-sm-6 col-md-4">
                <h3 style="align-items: center; justify-content: center; display: flex;">{{ request.user.name }} has {{ patients.count }} Patient/s</h3>
                <br>
                <br>
            </div>
        </div>
    </section>

    <section class="dentist-area section-padding-30-0">
        <div class="container">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col" class="text-center">Profile Photo</th>
                    <th scope="col">Name</th>
                    <th scope="col">Phone Number</th>
                    <th scope="col">Message</th>
                    <th scope="col">Date</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for patient in patients %}
                    <tr>
                        <td style="vertical-align: middle; display: flex; align-items: center;">
                            <div style="width: 50px; height: 50px; border-radius: 50%; overflow: hidden; margin: 0 auto;">
                                {% if patient.user.patientadditional.profile_photo %}
                                    <img src="{{ patient.user.patientadditional.profile_photo.url }}" alt="Profile Photo" style="width: 100%; height: 100%; object-fit: cover;">
                                {% else %}
                                    <img src="{% static 'images/default-profile-photo.jpg' %}" alt="Profile Photo" style="width: 100%; height: 100%; object-fit: cover;">
                                {% endif %}
                            </div>
                        </td>
                        <td style="vertical-align: middle;">{{ patient.user.name }}</td>
                        <td style="vertical-align: middle;">{{ patient.user.phone_number }}</td>
                        <td style="vertical-align: middle;">{{ patient.message }}</td>
                        <td style="vertical-align: middle;">{{ patient.date }}</td>
                        <td style="vertical-align: middle;" >
                            <a href="{% url 'appointment:delete-patient' patient.id %}">
                                <i class="far fa-trash-alt" style="visibility: visible;"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}

templates/appointment/service.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Service{% endblock %}

{% block content %}

  
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ***** Services Area Start ***** -->
  <section class="dentist-area section-padding-50-0">
   <center><h3 class="lead">Our Services</h3></center>

      </br>
    <div class="container">

      <div class="row">

        <!-- Single Service Area -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'img/123.jpg' %}" alt="">
            </div>
            <h5>Dentistry</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

        <!-- Single Service Area -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'img/123.jpg' %}" alt="">
            </div>
            <h5>Cardiology</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

        <!-- Single Service Area -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'img/123.jpg' %}" alt="">
            </div>
            <h5>ENT Specialists</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

        <!-- Single Service Area -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'img/123.jpg' %}" alt="">
            </div>
            <h5>Astrology</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

        <!-- Single Service Area -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'img/123.jpg' %}" alt="">
            </div>
            <h5>Neuroanatomy</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

        <!-- Single Service Area -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'img/123.jpg' %}" alt="">
            </div>
            <h5>Blood Screening</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

          <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'img/123.jpg' %}" alt="">
            </div>
            <h5>Eye Care</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

          <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'img/123.jpg' %}" alt="">
            </div>
            <h5>Physical Therapy</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

      </div>
    </div>
  </section>
  <!-- ***** Services Area End ***** -->

  <!-- ***** Testimonials Area Start ***** -->

{% endblock %}

templates/appointment/takeappointment_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Appointment Delete{% endblock %}

{% block content %}

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-lg-5 mb-5 mb-lg-0">
                <center>
                    <h4 class="highlight">Are you sure you want to delete this patient?</h4>

                </center>


                <form method="post">{% csrf_token %}

                    <table class="table">
                        <thead>
                        <tr>

                            <th scope="col">Name</th>
                            <th scope="col">Phone Number</th>
                            <th scope="col">Message</th>
                            <th scope="col">Date</th>


                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                             <td> {{ object.full_name }}</td>
                            <td> {{ object.phone_number }}</td>
                            <td>{{ object.message }}</td>
                            <td>{{ object.date }}</td>
                        </tr>
                        </br>
                        </br>
                        </tbody>
                    </table>
                    <center><input class="btn btn-danger" type="submit" value="Delete">
                    </center>


                </form>


                </br>

            </div>
        </div>
    </div>


{% endblock %}