accounts/urls.py
from django.urls import path
from .import views
from appointment.views import *

from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
# from accounts.views import *
app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('Patient_register/', views.patient_register, name='Patient_register'),
    path('Doctor_register/', views.doctor_register, name='Doctor_register'),
    path('login/', views.login_view_user, name='login'),
    path('', views.home_page_view, name='index'),

    path('logout/', views.logout_view, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_form.html", success_url=reverse_lazy("password_reset_complete")),
         name="password_reset_confirm"),  # 3
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html", success_url=reverse_lazy("password_reset_done"), email_template_name='registration/forgot_password_email.html'),
         name="reset_password"),     # 1
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"),
         name="password_reset_done"),    # 2

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_done.html"),
         name="password_reset_complete"),   # 4

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html', success_url=reverse_lazy("password_change_done")),
         name='password_change'),




]

appointment/urls.py
"""
doctor_appointment_system URL Configuration

"""

from django.urls import path
from appointment.views import *
from django.conf import settings
from django.conf.urls.static import static
from appointment import views

app_name = 'appointment'

urlpatterns = [

    # path('', HomePageView.as_view(), name='home'),
    path('service', views.service_view,  name='service'),
    path('<int:pk>/patient/delete/', views.delete_patient, name='delete-patient'),
    path('<int:pk>/doctor/delete/', views.delete_doctor, name='delete-doctor'),
    path('search/', views.search_view, name='search'),
    path('patient/', views.patient_list, name='patient-list'),
    path('doctor-list/', views.doctor_list, name='doctor-list'),

    path('patients/<id>/', views.doctordetails, name='doctor-detail'),
    path('detail/<int:id>/', views.display_cart, name='detail'),
    path('doctordetail/<id>/', views.view_doctor_detail, name='docdetail'),
    path('patient/profile/update/<id>/', views.editprofile, name='patient-profile-update'),
    path('doctor/profile/update/<id>/', views.editprofiledoctor, name='doctor-profile-update'),
    path('payment/<int:id>', views.payment, name = 'payment'),
    path('handlerequest/', views.handlerequest, name = 'handlerequest'),
    path('generateinvoice/<int:pk>/', views.GenerateInvoice.as_view(), name = 'generateinvoice'),
    


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docmed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url,  include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('appointment.urls')),

    url('', include('social_django.urls', namespace='social')),
]

templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.name }},
Thanks for signing up to Docmed!

To set up your account, Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

Thanks for using our site!

Sincerely,
Docmed Team

{% endautoescape %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

{% block content %}


<div class="breadcumb-area bg-img bg-gradient" style="background-image: url('{% static 'img/bg-img/14.jpg' %}');">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">

                <form id="job-main-form" method="get" action="{% url 'appointment:search' %}"
                    class="search-doctor-form">
                    <div class="row mb-5">


                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <input type="text" id="location" name="location" class="form-control form-control-lg"
                                placeholder="Any Location ?  Ex : Uttara, Dhaka">
                        </div>
                        {% comment %} <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <input type="text" id="name" name="name" class="form-control form-control-lg"
                                placeholder="Name">
                        </div> {% endcomment %}

                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <input type="text" id="your_expertise" name="your_expertise"
                                class="form-control form-control-lg" placeholder="Specialists">
                            {% comment %} <select id="department" name="your_expertise" class="form-control">
                                <option style="display: none;">Select Your Service</option>
                                <option>Cardiology</option>
                                <option>Dentistry</option>
                                <option>ENT Specialists</option>
                                <option>Astrology</option>
                                <option>Neuroanatomy</option>
                                <option>Blood Screening</option>
                                <option>Eye Care</option>
                                <option>Physical Therapy</option>
                            </select> {% endcomment %}
                        </div>


                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <button type="submit" class="btn btn-info btn-lg btn-block text-black btn-search"
                                style="font-size:90%; width: 20%; height :90%"><i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>


            </div>
        </div>
    </div>
</div>
<section class="section section-specialities">
    <div class="container-fluid">
        <div class="section-header text-center">
            <h2>Clinic and Specialities</h2>
            <p class="sub-title">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua.</p>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-9">
                <!-- Slider -->
                <div class="specialities-slider slider">

                    <!-- Slider Item -->
                    <div class="speicality-item text-center">
                        <div class="speicality-img">
                            <img src="{% static 'img/img/specialities/specialities-01.png'%}" class="img-fluid"
                                alt="Speciality">
                            <span><i class="fa fa-circle" aria-hidden="true"></i></span>
                        </div>
                        <p>Urology</p>
                    </div>
                    <!-- /Slider Item -->

                    <!-- Slider Item -->
                    <div class="speicality-item text-center">
                        <div class="speicality-img">
                            <img src="{% static 'img/img/specialities/specialities-02.png'%}" class="img-fluid"
                                alt="Speciality">
                            <span><i class="fa fa-circle" aria-hidden="true"></i></span>
                        </div>
                        <p>Neurology</p>
                    </div>
                    <!-- /Slider Item -->

                    <!-- Slider Item -->
                    <div class="speicality-item text-center">
                        <div class="speicality-img">
                            <img src="{% static 'img/img/specialities/specialities-03.png'%}" class="img-fluid"
                                alt="Speciality">
                            <span><i class="fa fa-circle" aria-hidden="true"></i></span>
                        </div>
                        <p>Orthopedic</p>
                    </div>
                    <!-- /Slider Item -->

                    <!-- Slider Item -->
                    <div class="speicality-item text-center">
                        <div class="speicality-img">
                            <img src="{% static 'img/img/specialities/specialities-04.png'%}" class="img-fluid"
                                alt="Speciality">
                            <span><i class="fa fa-circle" aria-hidden="true"></i></span>
                        </div>
                        <p>Cardiologist</p>
                    </div>
                    <!-- /Slider Item -->

                    <!-- Slider Item -->
                    <div class="speicality-item text-center">
                        <div class="speicality-img">
                            <img src="{% static 'img/img/specialities/specialities-05.png'%}" class="img-fluid"
                                alt="Speciality">
                            <span><i class="fa fa-circle" aria-hidden="true"></i></span>
                        </div>
                        <p>Dentist</p>
                    </div>
                    <!-- /Slider Item -->

                </div>
                <!-- /Slider -->

            </div>
        </div>
    </div>
</section>



{% if request.user.is_authenticated and request.user.is_Patient %}
<div class="container">
    <div class="col-lg-5" style="max-width: 100%;">
        <div class="doctor-slider slider">
            {% for apt in home %}

            <!-- Doctor Widget -->
            <div class="profile-widget">
                <div class="doc-img">
                    <a href="{% url 'appointment:docdetail' id=apt.id %}">
                        <img class="img-fluid" alt="User Image" src="{{ apt.user.showAppointment.get_image_url }}">
                    </a>
                    <a href="javascript:void(0)" class="fav-btn">
                        <i class="far fa-bookmark"></i>
                    </a>
                </div>
                <div class="pro-content">
                    <h3 class="title">
                        <a href="{% url 'appointment:docdetail' id=apt.id %}">{{ apt.user.name }}</a>
                        <i class="fas fa-check-circle verified"></i>
                    </h3>
                    <p class="speciality">{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                    <div class="rating">
                        <i class="fas fa-star filled"></i>
                        <i class="fas fa-star filled"></i>
                        <i class="fas fa-star filled"></i>
                        <i class="fas fa-star filled"></i>
                        <i class="fas fa-star filled"></i>
                        <span class="d-inline-block average-rating">(17)</span>
                    </div>
                    <ul class="available-info">
                        <li>
                            <i class="fas fa-map-marker-alt"></i> {{ apt.user.showAdditional.location }}
                        </li>
                        <li>
                            <i class="far fa-clock"></i> Available on {{ apt.start_time }} to {{ apt.end_time }}
                            in {{ apt.hospital_name }}
                        </li>
                        <li>
                            <i class="far fa-money-bill-alt"></i> $300 - $1000
                            <i class="fas fa-info-circle" data-toggle="tooltip" title="Lorem Ipsum"></i>
                        </li>
                    </ul>
                    <div class="row row-sm">
                        <div class="col-6">
                            <a href="{% url 'appointment:docdetail' id=apt.id %}" class="btn view-btn">View Profile</a>
                        </div>
                        <div class="col-6">
                            <a href="{% url 'appointment:doctor-detail' id=apt.id %}" class="btn book-btn">Book Now</a>
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
             {% elif request.user.is_authenticated and request.user.is_Doctor%}
            
             {% comment %} <div class="container"></div> {% endcomment %}
           {% else %}
           <div class="container">
            <div class="col-lg-5" style="max-width: 100%;">
                <div class="doctor-slider slider">
                    {% for apt in home %}
        
                    <!-- Doctor Widget -->
                    <div class="profile-widget">
                        <div class="doc-img">
                            <a href="{% url 'appointment:docdetail' id=apt.id %}">
                                <img class="img-fluid" alt="User Image" src="{{ apt.user.showAppointment.get_image_url }}">
                            </a>
                            <a href="javascript:void(0)" class="fav-btn">
                                <i class="far fa-bookmark"></i>
                            </a>
                        </div>
                        <div class="pro-content">
                            <h3 class="title">
                                <a href="{% url 'appointment:docdetail' id=apt.id %}">{{ apt.user.name }}</a>
                                <i class="fas fa-check-circle verified"></i>
                            </h3>
                            <p class="speciality">{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                            <div class="rating">
                                <i class="fas fa-star filled"></i>
                                <i class="fas fa-star filled"></i>
                                <i class="fas fa-star filled"></i>
                                <i class="fas fa-star filled"></i>
                                <i class="fas fa-star filled"></i>
                                <span class="d-inline-block average-rating">(17)</span>
                            </div>
                            <ul class="available-info">
                                <li>
                                    <i class="fas fa-map-marker-alt"></i> {{ apt.user.showAdditional.location }}
                                </li>
                                <li>
                                    <i class="far fa-clock"></i> Available on {{ apt.start_time }} to {{ apt.end_time }}
                                    in {{ apt.hospital_name }}
                                </li>
                                <li>
                                    <i class="far fa-money-bill-alt"></i> $300 - $1000
                                    <i class="fas fa-info-circle" data-toggle="tooltip" title="Lorem Ipsum"></i>
                                </li>
                            </ul>
                            <div class="row row-sm">
                                <div class="col-6">
                                    <a href="{% url 'appointment:docdetail' id=apt.id %}" class="btn view-btn">View Profile</a>
                                </div>
                                {% comment %} <div class="col-6">
                                    <a href="{% url 'appointment:doctor-detail' id=apt.id %}" class="btn book-btn">Book Now</a>
                                </div> {% endcomment %}
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                    {% endif %}
            
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; First</a>
                    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    {% endif %}

                    {% comment %} <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span> {% endcomment %}

                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>



{% endblock %}

templates/index1.html
{% extends 'base.html' %}
{% load static %}



{% block content %}


    <div class="breadcumb-area bg-img bg-gradient"  style="background-image: url('{% static 'img/bg-img/14.jpg' %}');">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="search-box">
            <form id="job-main-form" method="get" action="{% url 'appointment:search' %}">
                <div class="row mb-5">
                <div class="form-group search-location">
                    <input type="text"id="location" name="location"class="form-control" placeholder="Search Location">
                    <span class="form-text">Based on your Location</span>
                </div>
                <div class="form-group search-info">
                    <input type="text" id="your_expertise" name="your_expertise"class="form-control" placeholder="Search Doctors, Clinics, Hospitals, Diseases Etc">
                    <span class="form-text">Ex : Dental or Sugar Check up etc</span>
                </div>
                <button type="submit" class="btn btn-primary search-btn"><i class="fas fa-search"></i> <span>Search</span></button>
            </div>
            </form>
        </div>
      </div>
    </div>
  </div>



    <section class="dentist-area section-padding-50-0">

        <div class="container">







            <div class="row">

                <div class="col-12">
                    <div class="section-heading text-center">


                        <h3>We have found {{ appointment.count }} doctor/s. </h3>
                        <div class="line"></div>
                    </div>
                </div>
            </div>

            <div class="row">


                {% for apt in home %}
                {% comment %} {% for i in d_add %} {% endcomment %}
                {% comment %} {% for j in ds %} {% endcomment %}

                    <!-- Single Dentist Area -->
                    <div class="col-12 col-sm-6 col-md-4">
                        <div class="single-dentist-area mb-100">
                            <img style="height: 500px; width: 600px" src="{{ apt.user.showAppointment.get_image_url }}" alt="">
                            <!-- Dentist Content -->
                            <div class="dentist-content">
                                <!-- Social Info -->
                                <div class="dentist-social-info">

                                </div>
                                <!-- Dentist Info -->
                                <div class="dentist-info bg-dark bg-gradient-overlay">
                                    {% if request.user.is_authenticated and request.user.is_Patient %}
                    <h5>{{ apt.user.name }}</h5>
                    <p>{{ apt.user.showAdditional.your_expertise }} Expert</p>
                    <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>

                    <p>Available {{ apt.start_time }} to {{ apt.end_time }}
                        in {{ apt.hospital_name }}</p>
                    <p>
                        AT {{ apt.user.showAdditional.location }} <i class="fa fa-th"></i>
                        <a href="{% url 'appointment:doctor-detail' id=apt.id %}"> Take
                            Appointment</a>

                    </p>
                    {% elif request.user.is_authenticated and request.user.is_Doctor%}

                    <h5>{{ apt.user.name }}</h5>
                    <p>{{ apt.user.showAdditional.your_expertise }} Expert</p>
                    <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                    <p>Available {{ apt.start_time }} to {{ apt.end_time }}
                        in {{ apt.hospital_name }}</p>
                    <p>AT {{ apt.user.showAdditional.location }}</p>

                    {% else %}

                    <h5>{{ apt.user.name }}</h5>
                    <p>{{ apt.user.showAdditional.your_expertise }} Expert</p>
                    <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                    <p>Available {{ apt.start_time }} to {{ apt.end_time }}
                        in {{ apt.hospital_name }}</p>
                    <p>
                        AT {{ apt.user.showAdditional.location }} </p>


                    {% endif %}

                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            

                <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </span>
                </div>


            </div>

        </div>
    </section>


{% endblock %}

templates/nav.html
{% load static %}
<!-- Preloader -->
<!-- Preloader -->

<style>
	.nav-profile-photo {
		display: inline-block;
		width: 50px;  /* Adjust the width to your desired size */
		height: 50px;  /* Adjust the height to your desired size */
		border-radius: 50%;  /* Make the photo circular */
		object-fit: cover;  /* Maintain the aspect ratio and cover the container */
		margin-right: 5px;  /* Add some spacing to the right of the photo */
	  }</style>
<header class="header">
				<nav class="navbar navbar-expand-lg header-nav">
					<div class="navbar-header">
						<a id="mobile_btn" href="javascript:void(0);">
							<span class="bar-icon">
								<span></span>
								<span></span>
								<span></span>
							</span>
						</a>
						<a href="{%url 'accounts:index'%}" class="navbar-brand logo">
							<img src="{% static 'img/logo1.png' %}" class="img-fluid" alt="Logo">
						</a>
					</div>
					<div class="main-menu-wrapper">
						<div class="menu-header">
							<a href="{%url 'accounts:index'%}" class="menu-logo">
								<img src="{% static 'img/logo1.png' %}" class="img-fluid" alt="Logo">
							</a>
							<a id="menu_close" class="menu-close" href="javascript:void(0);">
								<i class="fas fa-times"></i>
							</a>
						</div>
						<ul class="main-nav">
							<li class="active">
								<a href="{%url 'accounts:index'%}">Home</a>
							</li>
							{% if request.user.is_authenticated and request.user.is_Patient %}
							<li class="has-submenu">
								<a href="#">Checkout <i class="fas fa-chevron-down"></i></a>
								<ul class="submenu">
									{% comment %} <li><a href="doctor-dashboard.html">Doctor Dashboard</a></li> {% endcomment %}
									<li><a href="{% url 'appointment:doctor-list' %}"> Your Appointments</a></li>
									
								</ul>
							</li>	
							
							<li>
								<a href="admin" target="_blank">Admin</a>
							</li>
							<li class="login-link">
								<a href="login.html">{{request.user.name}}</a>
							</li>
							{% elif request.user.is_authenticated and request.user.is_Doctor%}
							
							<li class="has-submenu">
								<a href="#">Checkout <i class="fas fa-chevron-down"></i></a>
								<ul class="submenu">
									<li><a href="{% url 'appointment:patient-list' %}">Patients</a></li>
									
									<li><a href="{% url 'appointment:doctor-profile-update' id=request.user.id  %}">Profile Settings</a></li>
									
								</ul>
							</li>	
							
							<li>
								<a href="admin" target="_blank">Admin</a>
							</li>
							<li class="login-link">
								<a href="login.html">{{request.user.name}}</a>
							</li>
							{% else %}
							
							<li>
								<a href="#" target="_blank">About</a>
							</li>
							<li>
								<a href="#" target="_blank">FAQs</a>
							</li><li>
								<a href="#" target="_blank">Services</a>
							</li>
							<li class="login-link">
								<a href="login.html">{{request.user.name}}</a>
							</li>
							{%endif%}
						</ul>		 
					</div>		 
					<ul class="nav header-navbar-rht">
						<li class="nav-item contact-item">
							<div class="header-contact-img">
								<i class="far fa-hospital"></i>							
							</div>
							<div class="header-contact-detail">
								<p class="contact-header">Contact</p>
								<p class="contact-info-header"> +91-4544614864</p>
							</div>
						</li>
						{% if request.user.is_authenticated and request.user.is_Patient %}
						<li class="nav-item">
							{% if request.user.patientadditional.profile_photo %}
							<a href="{% url 'appointment:patient-profile-update' id=request.user.id %}" class="nav-profile-photo">
								<img src="{{ request.user.patientadditional.profile_photo.url }}" alt="Profile Photo" class="nav-profile-photo">
							</a>
							{% else %}
							<a href="{% url 'appointment:patient-profile-update' id=request.user.id %}" class="nav-link header-login">
								{{ request.user.name }}
							</a>
						
							{% endif %}
						</li>
						<li class="nav-item">
							<a class="nav-link header-login" href="{% url 'accounts:logout' %}">logout</a>
						</li>
						{% elif request.user.is_authenticated and request.user.is_Doctor%}
						<li class="nav-item">
							{% if request.user.appointment.image %}
							<a href="{% url 'appointment:doctor-profile-update' id=request.user.id %}" class="nav-profile-photo">
								<img src="{{ request.user.appointment.image.url }}" alt="Profile Photo" class="nav-profile-photo">
							</a>
							{% else %}
								<a href="{% url 'appointment:doctor-profile-update' id=request.user.id %}" class="nav-link header-login">
        {{ request.user.name }}
    </a>

							{% endif %}
						</li>
						<li class="nav-item">
							<a class="nav-link header-login" href="{% url 'accounts:logout' %}">logout </a>
						</li>

						{%else%}
						<li class="nav-item">
							<a class="nav-link header-login" href="{% url 'accounts:Doctor_register' %}">Doctor/signup </a>
						</li>
						<li class="nav-item">
							<a class="nav-link header-login" href="{% url 'accounts:Patient_register' %}">Patient/signup </a>
						</li>
						<li class="nav-item">
							<a class="nav-link header-login" href="{% url 'accounts:login' %}">login </a>
						</li>
						{%endif%}
					</ul>
				</nav>
			</header>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Demo Registration</title>
</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Demo Registration</h2>
                </div>
                <div class="card-body">
                    <div class="row">
                       <div class="col-lg-6">
                        <a type="button" class="btn btn-block" href="{% url 'accounts:Patient_register' %}">I am a Patient</a>
                       </div>
                       <div class="col-lg-6">
                        <a type="button" class="btn btn-block" href="{% url 'accounts:Doctor_register' %}">I am an Doctor</a>
                       </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
  


</body>
</html>