appointment/urls.py
"""
doctor_appointment_system URL Configuration

"""

from django.urls import path
from appointment.views import *
from django.conf import settings
from django.conf.urls.static import static
from appointment import views

app_name = 'appointment'

urlpatterns = [

    # path('', HomePageView.as_view(), name='home'),
    path('service', views.service_view,  name='service'),
    path('<int:pk>/patient/delete/', views.delete_patient, name='delete-patient'),
    path('<int:pk>/doctor/delete/', views.delete_doctor, name='delete-doctor'),
    path('search/', views.search_view, name='search'),
    path('patient/', views.patient_list, name='patient-list'),
    path('doctor-list/', views.doctor_list, name='doctor-list'),

    path('patients/<id>/', views.doctordetails, name='doctor-detail'),
    path('detail/<int:id>/', views.display_cart, name='detail'),
    path('doctordetail/<id>/', views.view_doctor_detail, name='docdetail'),
    path('patient/profile/update/<id>/', views.editprofile, name='patient-profile-update'),
    path('doctor/profile/update/<id>/', views.editprofiledoctor, name='doctor-profile-update'),
    path('payment/<int:id>', views.payment, name = 'payment'),
    path('handlerequest/', views.handlerequest, name = 'handlerequest'),
    path('generateinvoice/<int:pk>/', views.GenerateInvoice.as_view(), name = 'generateinvoice'),
    


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docmed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url,  include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('appointment.urls')),

    url('', include('social_django.urls', namespace='social')),
]

appointment/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from accounts.models import CustomUser ,Doctor, DoctorAdditional,Patient 

from datetime import date, datetime

import appointment

# Create your models here.

# class Order(models.Model):
#     status_choices = (
#         (1, 'Not Packed'),
#         (2, 'Ready For Shipment'),
#         (3, 'Shipped'),
#         (4, 'Delivered')
#     )
#     payment_status_choices = (
#         (1, 'SUCCESS'),
#         (2, 'FAILURE' ),
#         (3, 'PENDING'),
#     )
    
#     user = models.ForeignKey(Patient, on_delete=models.CASCADE)
#     status = models.IntegerField(choices = status_choices, default=1)
    
    

#     total_amount = models.FloatField()
#     payment_status = models.IntegerField(choices = payment_status_choices, default=3)
#     order_id = models.CharField(unique=True, max_length=100, null=True, blank=True, default=None) 
#     datetime_of_payment = models.DateTimeField(default=timezone.now)
#     # related to razorpay
#     razorpay_order_id = models.CharField(max_length=500, null=True, blank=True)
#     razorpay_payment_id = models.CharField(max_length=500, null=True, blank=True)
#     razorpay_signature = models.CharField(max_length=500, null=True, blank=True)
    

#     def save(self, *args, **kwargs):
#         if self.order_id is None and self.datetime_of_payment and self.id:
#             self.order_id = self.datetime_of_payment.strftime('PAY2ME%Y%m%dODR') + str(self.id)
#         return super().save(*args, **kwargs)

#     def __str__(self):
#         return self.user.email + " " + str(self.id) 
class Appointment(models.Model):
    user = models.OneToOneField(Doctor,on_delete=models.CASCADE)
    #
    image = models.ImageField(null=True, blank=True)
    #
    start_time = models.CharField(max_length=10)
    end_time = models.CharField(max_length=10)
    qualification_name = models.CharField(max_length=100)
    institute_name = models.CharField(max_length=100)
    hospital_name = models.CharField(max_length=100)
    price= models.FloatField(max_length=10, default='500')
    # 
    created_at = models.DateTimeField(default=timezone.now)
    # 
    
    @property
    def get_image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return "/media/about.jpg"


    def __str__(self):
        return self.user.name
 
class TakeAppointment(models.Model):
    # 
    user = models.ForeignKey(Patient, on_delete=models.CASCADE)
    appointment = models.ForeignKey(Appointment,on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    date = models.DateField(auto_now_add=False,default=date.today)
    time = models.TimeField(auto_now_add=False,default=timezone.now)
    # time = models.TimeField()
    
    def __str__(self):
        return self.user.name

class Order(models.Model):
    status_choices = (
        (1, 'Not Packed'),
        (2, 'Ready For Shipment'),
        (3, 'Shipped'),
        (4, 'Delivered')
    )
    payment_status_choices = (
        (1, 'SUCCESS'),
        (2, 'FAILURE' ),
        (3, 'PENDING'),
    )
    
    take = models.ForeignKey(TakeAppointment, on_delete=models.CASCADE )
    status = models.IntegerField(choices = status_choices, default=1)
    
    

    total_amount = models.FloatField()
    payment_status = models.IntegerField(choices = payment_status_choices, default=3)
    order_id = models.CharField(unique=True, max_length=100, null=True, blank=True, default=None) 
    datetime_of_payment = models.DateTimeField(default=timezone.now)
    # related to razorpay
    razorpay_order_id = models.CharField(max_length=500, null=True, blank=True)
    razorpay_payment_id = models.CharField(max_length=500, null=True, blank=True)
    razorpay_signature = models.CharField(max_length=500, null=True, blank=True)
    
    created_at = models.DateTimeField(default=timezone.now)
    def save(self, *args, **kwargs):
        if self.order_id is None and self.datetime_of_payment and self.id:
            self.order_id = self.datetime_of_payment.strftime('PAY2ME%Y%m%dODR') + str(self.id)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.take.user.email + " " + str(self.id)  




class PatientAppointmentTrack(models.Model):
    # 
    user = models.OneToOneField(Patient,on_delete=models.CASCADE)
    # 
    price= models.FloatField(max_length=10, default='500')
    # 
    created_at = models.DateTimeField(default=timezone.now)
    appointment = models.ForeignKey(Order, on_delete = models.CASCADE)

    
    @property
    def get_image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return "/media/about.jpg"


    def __str__(self):
        return self.user.name

templates/payment/detail.html
{% extends 'base.html' %}
{% comment %} {% load static %}
{% block content %} {% endcomment %}
{% load static %}
{% block title %}

{% endblock %}
{% block css %}
<style>
</style>
{% endblock %}
    {% block content %}
<div class="info">
  <div class="container">
    <h1 style="text-align:center;">Payment Summary</h1>
<form method="POST" action="{% url 'appointment:payment' id %}">{% csrf_token %}
{%for i in cart%}
    Your Appointment to {{i.user.name}}
    {%endfor%}
    <br>
    <button class="btn btn-primary" type="submit">Proceed for Payment</button>
</form>

  </div>

</div>



{% endblock %}

templates/payment/emailinvoice.html
<div style="background-color: rgb(228, 228, 228);">
    <div style="margin: 20px; background-color: #fff;">

Hi {{ user.name }},
Your appointment with appointment id: {{order.order_id}} has been placed successfully.


{% comment %} {% for i in order.productinorder_set.all %}
{% comment %} Product:{{i.product}} Quantity:{{i.quantity}} Price:{{i.price}} {% endcomment %}

Total:{{order.total_amount}}

appointment has been taken .

We have attached the invoice for your appointment with this mail.

Thanks for trusting us and using our services!

Sincerely,
Docmed Team

    </div>
</div>

templates/payment/invoice.html
<!DOCTYPE html>
<html lang="en">
  {% comment %} {% load static %} {% endcomment %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Medical Receipt</title>
    {% load static %}
    <style>
        /* Add your CSS styles here */
        /* ... */

        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #fff;
        }

        header {
            text-align: center;
            background-color: #4CAF50;
            color: #fff;
            padding: 10px;
        }

        #logo {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-bottom: 10px;
        }

        #logo img {
            width: 60px;
            height: 60px;
        }

        h1 {
            font-size: 24px;
            margin-top: 10px;
            color: #333;
        }

        #company {
            text-align: right;
            margin-top: -40px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        table th, table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }

        table th {
            background-color: #4CAF50;
            color: #fff;
        }

        .total {
            font-weight: bold;
        }

        footer {
            text-align: center;
            padding: 10px;
        }
    </style>
</head>

<body>
    <header>
        <div id="logo">
          <img src="{% static 'img/img/specialities/specialities-02.png'%}" class="img-fluid"
          alt="Speciality">
        </div>
        <h1>Medical Receipt</h1>
        <div id="company">
            <div>Docmed</div>
            <div><a href="mailto:info.docmed@gmail.com">info.docmed@gmail.com</a></div>
            <div><a href="http://127.0.0.1:8000">www.docmed.com</a></div>
        </div>
    </header>

    <div class="table-container">
      <table>
          <thead>
              <tr>
                  <th>PRICE</th>
              </tr>
          </thead>
          <tbody>
              {% for i in order.appointment_set.all %}
              <tr>
                  <td>{{ i.price }} INR</td>
              </tr>
              {% endfor %}
              <tr>
                  {% comment %} <td class="total">TOTAL:</td> {% endcomment %}
                  <td class="total">{{ amount }} INR</td>
              </tr>
          </tbody>
      </table>
  </div>
  

    <p style="text-align: right; font-size: 12px;">*All values are in INR</p>

    <footer>
        Thank you for choosing Docmed.
    </footer>
</body>
</html>

templates/payment/paymentfailed.html
{% extends 'base.html' %}
{% comment %} {% extends 'base.html' %} {% endcomment %}
{% comment %} {% load static %}
{% block title %}

{% endblock %}
{% block css %}
<style>
</style>
{% endblock %}

{% block body %} {% endcomment %}

{% load static %}
{% block content %}
<div class="info">
<div class="container" style="text-align:center;">
<h1>Payment Failed</h1>
<h3>Sorry! Your payment has been failed. Please try again.</h3>
<br>
<p class="mainmessage">
In case your money has been deducted, money will be autorefunded in 7-10 days.
</p>
<br>
<p class="mainmessage">Thank You for choosing us. You can contact us for any queries or details.</p>
</div>
</div>
{% endblock %}


{% block js %}
<script>

</script>
{% endblock %}

templates/payment/paymentsuccess.html
{% extends 'base.html' %}
{% comment %} {% extends 'firstapp/basic.html' %} {% endcomment %}
{% comment %} {% load static %}
{% block title %}

{% endblock %}
{% block css %}
<style>
</style>
{% endblock %}

{% block body %} {% endcomment %}
{% load static %}
{% block content %}
<div class="info">
<div class="container" style="text-align:center;">
<h1>Payment Success</h1>
<br>
<h3>Congratulations! You have successfully done the payment.You can print invoice related to it.</h3>
<a class="btn btn-primary btn-lg signup-button" href="{% url "appointment:generateinvoice" pk=id %}">Print Invoice</a>
</div>
</div>
{% endblock %}


{% block js %}
<script>

</script>
{% endblock %}

templates/payment/paymentsummaryrazorpay.html
{% extends 'base.html' %}
{% comment %} {% extends 'base.html' %} {% endcomment %}
{% comment %} {% load static %}
{% block title %}
{% endblock %}
{% block css %}
<style>
</style>
{% endblock %}

{% block body %} {% endcomment %}
{% load static %}
{% block content %}
<div class="info">
  <div class="container">
    <h1 style="text-align:center;">Payment Summary</h1>
    Total Amount - {{order.total_amount}}
    <br>
    <button id="rzp-button1" class="btn btn-lg btn-primary btn-block" type="button">Pay Now</button>
  </div>

</div>



{% endblock %}


{% block js %}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
  var options = {
    "key": "{{razorpay_merchant_id}}", // Enter the Key ID generated from the Dashboard
    "amount": "{% widthratio final_price 1 100 %}", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "WonderShop",
    "description": "Test Transaction",
    "order_id": "{{order_id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "callback_url": "{{callback_url}}",
    "prefill": {
      "name": "{{request.user.name}}",
      "email": "{{request.user.email}}",
      "contact": "+91" + "{{request.user.phone_number}}"
    },
    "theme": {
      "color": "#2BA977"
    }
  };
  var rzp1 = new Razorpay(options);
  document.getElementById('rzp-button1').onclick = function (e) {
    rzp1.open();
    e.preventDefault();
  }
</script>
{% endblock %}